### ISSUE TITLE
💎 Self-developing DAO SC

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-contracts#155]
Our implementation of decentralized investment in technical and business development of the protocol.

## ⚠️ Problem

The platform is not developed self autonomously.

## 🚀 Solution

Consistent implementation of a self-developing DAO engaged in the construction of on-chain asset management platform.

### ✔️ Tokenized developed strategy logic

* [x] **StrategyLogic**

### 🟢 On-chain crowdsourcing and crowdfunding

* [x] #156
* [ ] **Gauge**: ecosystem revenue distributing
* [ ] **Builder**: Investor, Manager and Worker roles
* [ ] **Builder**: bounty for solving github issues
* [ ] **Builder**: bounty for creating verified github issues

### 🔜 DAO-guided engineering

* [ ] **Builder**: professions and competencies
* [ ] **Builder**: Engineer profession
* [ ] **Builder**: hourly rate

### 🔜 DAO-guided business development

* [ ] **Builder**: Business Developer profession

### 🔜 Provide profitability for investors

* enhancement
  * add roles, professions, competencies
  * worker and manager performance tracking
  * points / activity incentivization
  * integrations
* distribute $STBL allocation
* track proof
  * [ ] positive ROI on distance
