### ISSUE TITLE
Bridge SC

### ISSUE THREAD

**Issue by a17** [stabilitydao/stability-contracts#7]
# Stability Bridge contracts meta issue

* [ ] describe arch of bridging TOKEN lock -> ChildATOKEN mint -> burn -> ChildBTOKEN mint -> burn -> TOKEN unlock
* [x] #41 
* [ ] Integrate Bridge to Platform, add chain lib, change deployment flow
* `IInterChainAdapter` [protocols](https://www.alchemy.com/alternatives/layerzero)
  * [ ] #43 
  * [ ] #44
* [ ] TokenFactory, ChildERC20, ChildERC721
* [ ] `Bridge` contract

**Comment by a17** [comment]
postponed
